### ISSUE TITLE
Merge Async into httplug

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/httplug-async#1]
Looking at the Promise interface: whether the FIG will come up with one or not, we are gonna need our own, right?

I mean, we have `getResponse` and `getException` which are custom methods.

We have two options:

- In case the Promise PSR will have a generic `getResult` method, I propose use that instead of the upper two, drop our custom interface and wait for the PSR
- If no, we are going to have our custom promise interface anyway, so we can just use ours and merge this right away into httplug.

WDYT @joelwurtz @dbu?

**Comment by dbu** [comment]
i think that would be ok. we decided to not have a different temporary
namespace so we can just move the interfaces into the httplug repo.

**Comment by joelwurtz** [comment]
:+1:

**Comment by joelwurtz** [comment]
If FIG comes up with a PSR we will certainly have to change our interface, so we can change the method name at this time (and maybe providing an abstract class in the mean time for upgrading, and BC compatibilites)

**Comment by sagikazarmark** [comment]
Our interface can extend the PSR interface, can't it? So we definitely need a custom one because of the custom methods. If so, extending the PSR interface later is not even a bc break if they have the same method signatures for then and wait.

**Comment by joelwurtz** [comment]
depend on the interface it comes up, don't want to guess that :p

**Comment by dbu** [comment]
yeah. but either way we can merge the repositories i think.

**Comment by sagikazarmark** [comment]
Agree.

**Comment by dbu** [comment]
do we delete this repository now?

**Comment by sagikazarmark** [comment]
Not yet, until everything is changed to use httplug. Also, I would like to save the repo content to the package-history.
